In [2]:
import scanpy as sc
import glob
import os
import pandas as pd
import numpy as np

In [3]:
adata = sc.read_csv(glob.glob(os.path.abspath('data/*counts.csv'))[0]).T
meta = pd.read_csv(glob.glob(os.path.abspath('data/*metadata.csv'))[0])

In [4]:
adata.obs = meta

In [5]:
adata.obs

Unnamed: 0        group      Cell_type Cell_subtype
0     AAACCTGAGCAGATCG-1       KO.PD1       NK cells     NK cells
1     AAACCTGAGCCACGTC-1  control.IgG  Myeloid cells     Monocyte
2     AAACCTGAGCCTATGT-1       KO.IgG  Myeloid cells     Monocyte
3     AAACCTGAGTTCCACA-1  control.IgG  Myeloid cells         cDC1
4     AAACCTGCAAGAAGAG-1       KO.IgG  Myeloid cells         TAM2
...                  ...          ...            ...          ...
7624  TTTGTCAGTCAACATC-1       KO.PD1       NK cells     NK cells
7625  TTTGTCATCAGCGACC-1       KO.IgG        T cells         Treg
7626  TTTGTCATCCACTCCA-1  control.IgG        B cells      B cells
7627  TTTGTCATCTTCGGTC-1       KO.IgG       NK cells     NK cells
7628  TTTGTCATCTTGAGAC-1  control.PD1  Myeloid cells     Monocyte

[7629 rows x 4 columns]

In [8]:
adata.var_names.to_list()

['Mrpl15',
 'Lypla1',
 'Tcea1',
 'Atp6v1h',
 'Rb1cc1',
 '4732440D04Rik',
 'St18',
 'Pcmtd1',
 'Gm26901',
 'Rrs1',
 '2610203C22Rik',
 'Mybl1',
 'Vcpip1',
 '1700034P13Rik',
 'Sgk3',
 'Mcmdc2',
 'Snhg6',
 'Tcf24',
 'Cops5',
 'Cspp1',
 'Arfgef1',
 'Prex2',
 'Slco5a1',
 'Ncoa2',
 'Tram1',
 'Lactb2',
 'Eya1',
 'Gm9947',
 'Msc',
 'Terf1',
 'Rpl7',
 'Rdh10',
 'Stau2',
 'Ube2w',
 'Eloc',
 'Tmem70',
 'Ly96',
 'Jph1',
 'Il17a',
 'Il17f',
 'Mcm3',
 'Paqr8',
 'Efhc1',
 'Tram2',
 'Tmem14a',
 'Gm28836',
 'Khdc1a',
 'Khdc1c',
 'Khdc1b',
 'Kcnq5',
 'Ogfrl1',
 'B3gat2',
 'Smap1',
 'Sdhaf4',
 'Fam135a',
 'Lmbrd1',
 'Phf3',
 'Ptp4a1',
 'Ptp4a1.1',
 'Prim2',
 'Rab23',
 'Bag2',
 'Zfp451',
 'Bend6',
 'Dst',
 'Gm37233',
 'Ccdc115',
 'Imp4',
 'Ptpn18',
 'Gm28417',
 '4930568A12Rik',
 'Arhgef4',
 'Gm38336',
 'Fam168b',
 'Plekhb2',
 'Gm37068',
 'Hs6st1',
 'Uggt1',
 'Neurl3',
 'Arid5a',
 '4930403P22Rik',
 'Kansl3',
 'Lman2l',
 'Cnnm4',
 'Cnnm3',
 'Ankrd23',
 'Ankrd39',
 'Sema4c',
 'D430040D24Rik',
 'Fam178b',
 'Co

In [28]:
binary_matrix = (adata.X > 0).astype(int)
groups = adata.obs['group'].unique()
print(groups)

['KO.PD1' 'control.IgG' 'KO.IgG' 'control.PD1']


In [32]:
for group in groups:
    # Get mask for current group
    group_mask = adata.obs['group'] == group
    print(group_mask)

0        True
1       False
2       False
3       False
4       False
        ...  
7624     True
7625    False
7626    False
7627    False
7628    False
Name: group, Length: 7629, dtype: bool
0       False
1        True
2       False
3        True
4       False
        ...  
7624    False
7625    False
7626     True
7627    False
7628    False
Name: group, Length: 7629, dtype: bool
0       False
1       False
2        True
3       False
4        True
        ...  
7624    False
7625     True
7626    False
7627     True
7628    False
Name: group, Length: 7629, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...  
7624    False
7625    False
7626    False
7627    False
7628     True
Name: group, Length: 7629, dtype: bool


In [35]:
group_cells = binary_matrix[group_mask]
print(group_cells)
group_expression = adata.X[group_mask]
print(group_expression)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 1 0]
 [0 1 1 ... 0 0 1]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [2. 0. 2. ... 0. 0. 0.]
 [2. 0. 1. ... 0. 3. 0.]
 [0. 1. 1. ... 0. 0. 1.]]


In [37]:
percent_expressed = np.array(group_cells.mean(axis=0)).flatten() * 100
percent_expressed

array([20.49780381,  9.61444607, 34.45583211, ...,  0.04880429,
       24.20693021, 13.42118106])

In [38]:
mean_expression = np.array(group_expression.mean(axis=0)).flatten()

In [39]:
mean_expression

array([0.25475842, 0.10736945, 0.4680332 , ..., 0.00048804, 0.35139093,
       0.16739874], dtype=float32)